### ISSUE TITLE
webui 沒有輸入負面提示的圖片無法解析

### ISSUE THREAD

**Issue by hbl917070** [Akegarasu/novelai-tagreader#5]
使用 stable-diffusion-webui 產生的圖片，如果沒有輸入負面提示，就不會有「Negative prompt: 」的字串，導致解析失敗
例如這張圖
[https://cdn.discordapp.com/attachments/896768892003823627/1046549815397449788/13300-627307634-rabbit_best_quality_masterpiece_highres.png](https://cdn.discordapp.com/attachments/896768892003823627/1046549815397449788/13300-627307634-rabbit_best_quality_masterpiece_highres.png)

**Comment by Akegarasu** [comment]
fixed
